export interface IEmail {
    id:number
    sender:string
    title:string
    date:string
    body: string
    read: boolean
    file:string | null
}

export interface ISelectableEmail extends IEmail{
    selected:boolean
}

export const emails3 = [{"id":1,"sender":"Brion Probets","title":"Nullam molestie nibh in lectus.","date":"2023-03-23"},
{"id":2,"sender":"Angel Tooting","title":"Proin risus.","date":"2022-12-06"},
{"id":3,"sender":"Dredi Struys","title":"Proin interdum mauris non ligula pellentesque ultrices.","date":"2023-05-04"},
{"id":4,"sender":"Tammie Dewane","title":"Etiam faucibus cursus urna.","date":"2023-05-19"},
{"id":5,"sender":"Conrado Janicki","title":"Aliquam sit amet diam in magna bibendum imperdiet.","date":"2022-09-28"},
{"id":6,"sender":"Gabrielle Barrett","title":"Aenean sit amet justo.","date":"2022-09-15"},
{"id":7,"sender":"Errol Sinnat","title":"Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","date":"2022-08-28"},
{"id":8,"sender":"Reena Ouslem","title":"Donec ut dolor.","date":"2023-02-09"},
{"id":9,"sender":"Ethelbert Sidden","title":"Nullam porttitor lacus at turpis.","date":"2022-08-03"},
{"id":10,"sender":"Maurise Houndesome","title":"Suspendisse potenti.","date":"2022-11-23"},
{"id":11,"sender":"Perren Snap","title":"Morbi ut odio.","date":"2022-09-15"},
{"id":12,"sender":"Jenifer Hargey","title":"Suspendisse potenti.","date":"2023-05-03"},
{"id":13,"sender":"Dee Thurborn","title":"Mauris lacinia sapien quis libero.","date":"2022-08-27"},
{"id":14,"sender":"Edmon Kleinsmuntz","title":"Cras non velit nec nisi vulputate nonummy.","date":"2022-09-15"},
{"id":15,"sender":"Raquel Gimson","title":"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.","date":"2023-05-21"},
{"id":16,"sender":"Valeda Fryd","title":"Fusce consequat.","date":"2022-09-19"},
{"id":17,"sender":"Carlita Smitham","title":"Etiam vel augue.","date":"2023-01-06"},
{"id":18,"sender":"Rebeka Ludlem","title":"Donec ut mauris eget massa tempor convallis.","date":"2022-08-30"},
{"id":19,"sender":"Drusie Buckell","title":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","date":"2023-07-06"},
{"id":20,"sender":"Charlotte Aickin","title":"Integer ac neque.","date":"2023-06-25"},
{"id":21,"sender":"Alanna Crix","title":"Etiam faucibus cursus urna.","date":"2023-05-07"},
{"id":22,"sender":"Briant Gauvain","title":"Quisque ut erat.","date":"2022-09-29"},
{"id":23,"sender":"Cam Glanert","title":"In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","date":"2023-03-06"},
{"id":24,"sender":"Harlin Lowsely","title":"Duis mattis egestas metus.","date":"2023-07-01"},
{"id":25,"sender":"Tammy Caddens","title":"Praesent blandit lacinia erat.","date":"2022-08-29"},
{"id":26,"sender":"Giselle Zaniolini","title":"Praesent id massa id nisl venenatis lacinia.","date":"2022-10-28"},
{"id":27,"sender":"Elias Ivachyov","title":"Duis bibendum.","date":"2022-10-11"},
{"id":28,"sender":"Tyson Meredyth","title":"In eleifend quam a odio.","date":"2023-06-20"},
{"id":29,"sender":"Wood Clemot","title":"In hac habitasse platea dictumst.","date":"2023-06-25"},
{"id":30,"sender":"Roberto Imorts","title":"Donec ut mauris eget massa tempor convallis.","date":"2023-05-13"},
{"id":31,"sender":"Abbott Port","title":"Duis aliquam convallis nunc.","date":"2022-08-10"},
{"id":32,"sender":"Hans Hugonnet","title":"Phasellus sit amet erat.","date":"2022-11-13"},
{"id":33,"sender":"Pru Cockrill","title":"Phasellus id sapien in sapien iaculis congue.","date":"2023-01-31"},
{"id":34,"sender":"Sheela Baselio","title":"Cras pellentesque volutpat dui.","date":"2023-05-01"},
{"id":35,"sender":"Katerina Newcombe","title":"Duis mattis egestas metus.","date":"2023-04-04"},
{"id":36,"sender":"Amalea Derisly","title":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","date":"2023-03-01"},
{"id":37,"sender":"Susanna Glanister","title":"Vestibulum ac est lacinia nisi venenatis tristique.","date":"2022-11-16"},
{"id":38,"sender":"Uta Ferry","title":"Etiam pretium iaculis justo.","date":"2022-11-01"},
{"id":39,"sender":"Maynard Titchener","title":"Nulla tempus.","date":"2023-04-13"},]

export const emails2 : Array<IEmail> = [{"id":1,"sender":"Barbette Long","title":"Sed ante.","body":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","date":"2021-04-08","read":true,"file":null},
{"id":2,"sender":"Theodor Vittet","title":"Nulla ac enim.","body":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.","date":"2022-06-11","read":true,"file":"LectusPellentesqueAt.tiff"},
{"id":3,"sender":"Vilhelmina Glaysher","title":"In est risus, auctor sed, tristique in, tempus sit amet, sem.","body":"Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","date":"2021-11-20","read":true,"file":null},
{"id":4,"sender":"Desmond Faires","title":"Nulla tempus.","body":"In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.","date":"2022-05-25","read":true,"file":null},
{"id":5,"sender":"Sheryl De Bernardi","title":"Suspendisse potenti.","body":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","date":"2022-10-26","read":true,"file":"CondimentumNeque.ppt"},
{"id":6,"sender":"Danice Syversen","title":"Mauris sit amet eros.","body":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","date":"2023-02-19","read":true,"file":null},
{"id":7,"sender":"Vincents Calvert","title":"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.","body":"Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","date":"2023-05-07","read":false,"file":"AugueVestibulum.xls"},
{"id":8,"sender":"Beth Malenoir","title":"Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","body":"Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.","date":"2021-12-09","read":true,"file":null},
{"id":9,"sender":"Doreen Tripcony","title":"Sed vel enim sit amet nunc viverra dapibus.","body":"Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.","date":"2022-10-15","read":true,"file":"RutrumRutrum.jpeg"},
{"id":10,"sender":"Pablo Jerratsch","title":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla.","body":"Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","date":"2021-06-20","read":false,"file":null},
{"id":11,"sender":"Bambie Petera","title":"Duis mattis egestas metus.","body":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.","date":"2020-09-27","read":false,"file":"Pellentesque.xls"},
{"id":12,"sender":"Sky Fader","title":"Cras in purus eu magna vulputate luctus.","body":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","date":"2023-01-03","read":false,"file":null},
{"id":13,"sender":"Hobard Bordone","title":"Cras non velit nec nisi vulputate nonummy.","body":"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.","date":"2022-05-28","read":true,"file":null},
{"id":14,"sender":"Livvie Knoble","title":"Donec ut mauris eget massa tempor convallis.","body":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.","date":"2023-05-11","read":true,"file":null},
{"id":15,"sender":"Perkin Smiley","title":"Praesent lectus.","body":"Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.","date":"2021-08-30","read":false,"file":null},
{"id":16,"sender":"Simone Huckstepp","title":"Fusce consequat.","body":"Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.","date":"2022-04-09","read":false,"file":null},
{"id":17,"sender":"Padgett Jays","title":"In hac habitasse platea dictumst.","body":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","date":"2021-09-13","read":true,"file":"CumSociisNatoque.mpeg"},
{"id":18,"sender":"Mathilda Gerritsma","title":"Nulla mollis molestie lorem.","body":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","date":"2023-05-03","read":false,"file":null},
{"id":19,"sender":"Hildagarde Hyne","title":"Maecenas pulvinar lobortis est.","body":"Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.","date":"2021-12-06","read":true,"file":null},
{"id":20,"sender":"Nat Galvin","title":"Maecenas tincidunt lacus at velit.","body":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","date":"2022-04-13","read":true,"file":null},
{"id":21,"sender":"Archie Duncombe","title":"In quis justo.","body":"Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.","date":"2020-11-24","read":false,"file":"Bibendum.txt"},
{"id":22,"sender":"Janessa De Dei","title":"In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","body":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","date":"2021-06-06","read":false,"file":null},
{"id":23,"sender":"Dorris Overstall","title":"Maecenas ut massa quis augue luctus tincidunt.","body":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.","date":"2022-06-19","read":false,"file":null},
{"id":24,"sender":"Salomo Rowcastle","title":"Morbi quis tortor id nulla ultrices aliquet.","body":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.","date":"2022-07-06","read":false,"file":null},
{"id":25,"sender":"Caron Baudino","title":"In congue.","body":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","date":"2021-10-03","read":false,"file":null},
{"id":26,"sender":"Lois Wedlake","title":"Phasellus in felis.","body":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.","date":"2022-12-02","read":false,"file":"ElitProin.tiff"},
{"id":27,"sender":"Lyon Grigorkin","title":"Fusce consequat.","body":"Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","date":"2023-05-25","read":true,"file":"Massa.png"},
{"id":28,"sender":"Melisa Ayars","title":"Sed ante.","body":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.","date":"2021-03-13","read":true,"file":null},
{"id":29,"sender":"Obed Lestor","title":"Donec semper sapien a libero.","body":"Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.","date":"2021-05-05","read":true,"file":null},
{"id":30,"sender":"Con Hasnney","title":"Duis mattis egestas metus.","body":"In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","date":"2021-11-20","read":true,"file":"PortaVolutpatErat.txt"},
{"id":31,"sender":"Osborne Moncreif","title":"Maecenas rhoncus aliquam lacus.","body":"Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","date":"2021-09-02","read":true,"file":null},
{"id":32,"sender":"Tomaso Penton","title":"Morbi vel lectus in quam fringilla rhoncus.","body":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.","date":"2022-07-10","read":false,"file":null},
{"id":33,"sender":"Lauryn Willmot","title":"Integer tincidunt ante vel ipsum.","body":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","date":"2023-04-01","read":false,"file":null},
{"id":34,"sender":"Ella Lucken","title":"Morbi porttitor lorem id ligula.","body":"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","date":"2021-12-30","read":true,"file":"FelisSed.jpeg"},
{"id":35,"sender":"Bartolomeo Duncklee","title":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.","body":"Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","date":"2023-03-16","read":false,"file":null},
{"id":36,"sender":"Jessy Trewartha","title":"Integer non velit.","body":"Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","date":"2023-07-11","read":true,"file":null},
{"id":37,"sender":"Madalyn Sirett","title":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.","body":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.","date":"2020-11-02","read":false,"file":null},
{"id":38,"sender":"Pearline Stenning","title":"Phasellus id sapien in sapien iaculis congue.","body":"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.","date":"2021-04-26","read":true,"file":"RhoncusMaurisEnim.txt"},
{"id":39,"sender":"Kelly Oldaker","title":"Nulla nisl.","body":"Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.","date":"2021-05-17","read":false,"file":null},
{"id":40,"sender":"Eilis Whyte","title":"Morbi porttitor lorem id ligula.","body":"Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","date":"2021-08-01","read":false,"file":null},
{"id":41,"sender":"Sibylla Moxon","title":"Mauris sit amet eros.","body":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.","date":"2020-10-22","read":false,"file":null},
{"id":42,"sender":"Ulrikaumeko Comi","title":"Nullam sit amet turpis elementum ligula vehicula consequat.","body":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.","date":"2021-06-14","read":false,"file":"UtDolorMorbi.jpeg"},
{"id":43,"sender":"Blair Copo","title":"Proin at turpis a pede posuere nonummy.","body":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","date":"2021-05-10","read":false,"file":null},
{"id":44,"sender":"Cicely Croxley","title":"Donec ut mauris eget massa tempor convallis.","body":"Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","date":"2022-09-25","read":false,"file":"VelitEuEst.mpeg"},
{"id":45,"sender":"Conni Screase","title":"In hac habitasse platea dictumst.","body":"Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","date":"2022-08-31","read":false,"file":null}]

function toUSFormat(date : string){
    const dateAsAnArray = date.split('-')
    return dateAsAnArray[1] + '/' + dateAsAnArray[2] + '/' + dateAsAnArray[0]
}

export const emails : Array<ISelectableEmail> = emailsToSelectableEmails([...emails2].map(email => {
    return {...email, date : toUSFormat(email.date)}
}))

function emailsToSelectableEmails(emailsList : Array<IEmail>){
    return emailsList.map(email => {
        const newEmail : ISelectableEmail = {...email, selected : false}
        return newEmail
    })
}
